module.exports = {
  content: ["./_site/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        neutral: {
          DEFAULT: "rgba(113, 113, 122), <alpha-value>)",
          light: "rgba(244, 244, 245, <alpha-value>)",
          dark: "rgba(24, 24, 27, <alpha-value>)",
          50: "rgba(250, 250, 250, <alpha-value>)",
          100: "rgba(244, 244, 245, <alpha-value>)",
          200: "rgba(228, 228, 231), <alpha-value>)",
          300: "rgba(212, 212, 216, <alpha-value>)",
          400: "rgba(161, 161, 170), <alpha-value>)",
          500: "rgba(113, 113, 122, <alpha-value>)",
          600: "rgba(82, 82, 91, <alpha-value>)",
          700: "rgba(63, 63, 70, <alpha-value>)",
          800: "rgba(39, 39, 42, <alpha-value>)",
          900: "rgba(24, 24, 27, <alpha-value>)",
        },
        primary: {
          DEFAULT: "rgba(35, 134, 233;, <alpha-value>)",
          light: "rgba(35, 134, 233;, <alpha-value>)",
          dark: "rgba(35, 134, 233;, <alpha-value>)",
          50: "rgba(35, 134, 233;, <alpha-value>)",
          100: "rgba(35, 134, 233;, <alpha-value>)",
          200: "rgba(35, 134, 233;, <alpha-value>)",
          300: "rgba(35, 134, 233;, <alpha-value>)",
          400: "rgba(35, 134, 233;, <alpha-value>)",
          500: "rgba(35, 134, 233;, <alpha-value>)",
          600: "rgba(35, 134, 233;, <alpha-value>)",
          700: "rgba(35, 134, 233;, <alpha-value>)",
          800: "rgba(35, 134, 233;, <alpha-value>)",
          900: "rgba(35, 134, 233;, <alpha-value>)",
        },
        secondary: {
          DEFAULT: "rgba(240, 21, 114, <alpha-value>)",
          light: "rgba(254, 82, 151, <alpha-value>))",
          dark: "rgba(191, 0, 92, <alpha-value>))",
          50: "rgba(255, 108, 167, <alpha-value>))",
          100: "rgba(254, 95, 159, <alpha-value>))",
          200: "rgba(254, 82, 151, <alpha-value>))",
          300: "rgba(251, 57, 136, <alpha-value>))",
          400: "rgba(247, 37, 123, <alpha-value>))",
          500: "rgba(240, 21, 114, <alpha-value>))",
          600: "rgba(232, 11, 107, <alpha-value>))",
          700: "rgba(220, 4, 101, <alpha-value>))",
          800: "rgba(206, 0, 96, <alpha-value>))",
          900: "rgba(191, 0, 92, <alpha-value>))",
        },
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            "--tw-prose-body": theme("colors.neutral.700 / 1"),
            "--tw-prose-headings": theme("colors.neutral.800 / 1"),
            "--tw-prose-lead": theme("colors.neutral.500 / 1"),
            "--tw-prose-links": theme("colors.primary.700 / 1"),
            "--tw-prose-bold": theme("colors.neutral.900 / 1"),
            "--tw-prose-counters": theme("colors.neutral.800 / 1"),
            "--tw-prose-bullets": theme("colors.neutral.500 / 1"),
            "--tw-prose-hr": theme("colors.neutral.200 / 1"),
            "--tw-prose-quotes": theme("colors.neutral.700 / 1"),
            "--tw-prose-quote-borders": theme("colors.primary.200 / 1"),
            "--tw-prose-captions": theme("colors.neutral.500 / 1"),
            "--tw-prose-code": theme("colors.secondary.700 / 1"),
            "--tw-prose-pre-code": theme("colors.neutral.700 / 1"),
            "--tw-prose-pre-bg": theme("colors.neutral.50 / 1"),
            "--tw-prose-th-borders": theme("colors.neutral.500 / 1"),
            "--tw-prose-td-borders": theme("colors.neutral.300 / 1"),
            "--tw-prose-invert-body": theme("colors.neutral.300 / 1"),
            "--tw-prose-invert-headings": theme("colors.neutral.50 / 1"),
            "--tw-prose-invert-lead": theme("colors.neutral.500 / 1"),
            "--tw-prose-invert-links": theme("colors.primary.400 / 1"),
            "--tw-prose-invert-bold": theme("colors.neutral.DEFAULT / 1"),
            "--tw-prose-invert-counters": theme("colors.neutral.400 / 1"),
            "--tw-prose-invert-bullets": theme("colors.neutral.600 / 1"),
            "--tw-prose-invert-hr": theme("colors.neutral.500 / 1"),
            "--tw-prose-invert-quotes": theme("colors.neutral.200 / 1"),
            "--tw-prose-invert-quote-borders": theme("colors.primary.900 / 1"),
            "--tw-prose-invert-captions": theme("colors.neutral.400 / 1"),
            "--tw-prose-invert-code": theme("colors.secondary.400 / 1"),
            "--tw-prose-invert-pre-code": theme("colors.neutral.200 / 1"),
            "--tw-prose-invert-pre-bg": theme("colors.neutral.700 / 1"),
            "--tw-prose-invert-th-borders": theme("colors.neutral.500 / 1"),
            "--tw-prose-invert-td-borders": theme("colors.neutral.700 / 1"),
            a: {
              textDecoration: "underline",
              textDecorationColor: theme("colors.primary.300 / 1"),
              fontWeight: "500",
              "&:hover": {
                color: theme("colors.neutral.DEFAULT / 1"),
                textDecoration: "none",
                backgroundColor: theme("colors.primary.600 / 1"),
                borderRadius: "0.09rem",
              },
            },
            "a code": {
              color: "var(--tw-prose-code)",
            },
            kbd: {
              backgroundColor: theme("colors.neutral.200 / 1"),
              padding: "0.1rem 0.4rem",
              borderRadius: "0.25rem",
              fontSize: "0.9rem",
              fontWeight: "600",
            },
            mark: {
              color: theme("colors.neutral.800 / 1"),
              backgroundColor: theme("colors.secondary.200 / 1"),
              padding: "0.1rem 0.2rem",
              borderRadius: "0.12rem",
            },
          },
        },
        invert: {
          css: {
            a: {
              textDecorationColor: theme("colors.neutral.600 / 1"),
            },
            kbd: {
              color: theme("colors.neutral.200 / 1"),
              backgroundColor: theme("colors.neutral.700 / 1"),
            },
            mark: {
              backgroundColor: theme("colors.secondary.400 / 1"),
            },
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
